
frameworkVersion: '3'

functions:
  api:
    events:
      - httpApi: 'GET /'
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper-analytics:${param:sha}
    timeout: 10

package:
  exclude:
    - venv/**
      # athena:GetWorkGroup

provider:
  iamRoleStatements:
    - Action:
        - 'athena:GetWorkGroup'
        - 'athena:StartQueryExecution'
      Effect: Allow
      Resource: '*'
  name: aws

service: wheelerrecommends-scraper-analytics
