
frameworkVersion: '3'

functions:
  api:
    events:
      - httpApi: 'GET /'
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper-analytics:${param:sha}
    memorySize: 1024
    timeout: 300

package:
  exclude:
    - venv/**

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'athena:BatchGetQueryExecution'
        - 'athena:GetDatabase'
        - 'athena:GetDataCatalog'
        - 'athena:GetQueryExecution'
        - 'athena:GetQueryResults'
        - 'athena:GetQueryResultsStream'
        - 'athena:GetTable'
        - 'athena:GetTableMetadata'
        - 'athena:GetWorkGroup'
        - 'athena:ListDatabases'
        - 'athena:ListDataCatalogs'
        - 'athena:ListEngineVersions'
        - 'athena:ListQueryExecutions'
        - 'athena:ListTableMetadata'
        - 'athena:ListWorkGroups'
        - 'athena:StartQueryExecution'
        - 'athena:StopQueryExecution'
        - 'glue:GetDatabase'
        - 'glue:GetTable'
        - 'glue:GetPartition'
        - 'glue:GetPartitions'
        - 's3:GetBucketLocation'
        - 's3:ListBucket'
        - 's3:GetObject'
        - 's3:PutObject'
      Resource: '*'

service: wheelerrecommends-scraper-analytics
