
frameworkVersion: '3'

functions:
  api:
    events:
      - httpApi: 'GET /'
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper-analytics:${param:sha}
    memorySize: 10240 # TODO: scale this down! TESTING ONLY
    timeout: 60

package:
  exclude:
    - venv/**

provider:
  iamRoleStatements:
    - Action:
        - 'athena:GetQueryResultsStream'
        - 'athena:GetWorkGroup'
        - 'athena:StartQueryExecution'
        - 's3:GetBucketLocation'
      Effect: Allow
      Resource: '*'
  name: aws

service: wheelerrecommends-scraper-analytics
