
frameworkVersion: '3'

functions:
  api:
    events:
      - httpApi: 'GET /'
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper-analytics:${param:sha}
    memorySize: 1024
    timeout: 300

package:
  exclude:
    - venv/**

provider:
  iamRoleStatements:
    - Action:
        - 's3:GetBucketLocation'
        - 's3:ListBucket'
        - 's3:GetObject'
        - 's3:PutObject'
        - 'athena:GetWorkGroup'
        - 'athena:GetDatabase'
        - 'athena:GetQueryResults'
        - 'athena:GetTable'
        - 'athena:StartQueryExecution'
        - 'glue:GetDatabase'
        - 'glue:GetTable'
        - 'glue:GetPartition'
        - 'glue:GetPartitions'
      Effect: Allow
      Resource: '*'
  name: aws

service: wheelerrecommends-scraper-analytics
