
frameworkVersion: '3'

functions:
  api:
    events:
      - httpApi: 'GET /'
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper-analytics:${param:sha}
    memorySize: 2048
    timeout: 28

package:
  exclude:
    - .venv/**

provider:
  name: aws
  iamRoleStatements:
    - Effect: Allow
      Action:
        - athena:GetDatabase
        - athena:GetDataCatalog
        - athena:GetQueryExecution
        - athena:GetQueryResults
        - athena:GetQueryResultsStream
        - athena:GetTable
        - athena:GetTableMetadata
        - athena:GetWorkGroup
        - athena:StartQueryExecution
        - athena:StopQueryExecution
      Resource: '*'
    - Effect: Allow
      Action:
        - glue:GetDatabase
        - glue:GetPartition
        - glue:GetPartitions
        - glue:GetTable
      Resource:
        - arn:aws:glue:${aws:region}:${aws:accountId}:catalog
        - arn:aws:glue:${aws:region}:${aws:accountId}:database/wheelerrecommends-scraper-database
        - arn:aws:glue:${aws:region}:${aws:accountId}:table/wheelerrecommends-scraper-database/home_page
        - arn:aws:glue:${aws:region}:${aws:accountId}:table/wheelerrecommends-scraper-database/movie_details_page
    - Effect: Allow
      Action:
        - s3:GetBucketLocation
        - s3:GetObject
        - s3:ListBucket
      Resource:
        - arn:aws:s3:::wheelerrecommends-scraper-data/*
        - arn:aws:s3:::wheelerrecommends-scraper-data
    - Effect: Allow
      Action:
        - s3:GetBucketLocation
        - s3:GetObject
        - s3:ListBucket
        - s3:PutObject
      Resource:
        - arn:aws:s3:::wheelerrecommends-scraper-logs/*
        - arn:aws:s3:::wheelerrecommends-scraper-logs

service: wheelerrecommends-scraper-analytics
