
service: wheelerrecommends-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    description: 'serverless web scraper'
    events:
      - schedule: rate(6 hours)
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper:${param:sha}
    timeout: 300

package:
  exclude:
    - venv/**
