
service: wheelerrecommends-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Effect: Allow
      Resource: 'arn:aws:s3:::wheelerrecommends-scraper-data/*'

functions:
  api:
    description: 'serverless web scraper'
    events:
     - schedule:
         rate: cron(0 15 * * * *)
         enabled: true
         input:
           page: home
           view_more_clicks: 9

     - schedule:
         rate: cron(0 45 * * * *)
         enabled: true
         input:
           page: movie_details
           movie_id: random

    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper:${param:sha}
    timeout: 300

package:
  exclude:
    - venv/**
