
frameworkVersion: '3'

functions:
  api:
    events:
     - schedule:
         rate: cron(15 * * * ? *) # minutes, hours, day-of-month, month, day-of-week, year
         enabled: true
         input:
           page: home
           view_more_clicks: 9
     - schedule:
         rate: rate(9 minutes)
         enabled: true
         input:
           page: movie_details
           movie_id: random
    description: 'serverless web scraper'
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper:${param:sha}
    timeout: 300

package:
  exclude:
    - .venv/**

provider:
  iamRoleStatements:
    - Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Effect: Allow
      Resource: 'arn:aws:s3:::wheelerrecommends-scraper-data/*'
  name: aws

service: wheelerrecommends-scraper
