
service: wheelerrecommends-scraper

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: handler.main
    events:
      - schedule: rate(24 hours)

package:
  exclude:
    - node_modules/**
    - venv/**

