
service: wheelerrecommends-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    description: 'serverless web scraper'
    events:
      - schedule: rate(6 hours)
    image:
      uri: ${param:ecr-image-uri}
    timeout: 300

package:
  exclude:
    - node_modules/**
    - venv/**
