
service: wheelerrecommends-scraper

frameworkVersion: '3'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.9
  ecr:
    images:
      appimage:
        path: ./

functions:
  api:
    handler: handler.main
    image:
      name: appimage
    timeout: 60
    events:
      - schedule: rate(24 hours)

package:
  exclude:
    - node_modules/**
    - venv/**

