
service: wheelerrecommends-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    events:
      - schedule: rate(24 hours)
    image:
      uri: 778263278211.dkr.ecr.us-east-1.amazonaws.com/wheelerrecommends-scraper:74993d6e18a6ac6ae192c6ce4cdf9459c5f88e52
    timeout: 300

package:
  exclude:
    - node_modules/**
    - venv/**
