
service: wheelerrecommends-scraper

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  iamRoleStatements:
    - Action:
        - 's3:GetObject'
        - 's3:PutObject'
      Effect: Allow
      Resource: 'arn:aws:s3:::wheelerrecommends-scraper-data/*'

functions:
  api:
    description: 'serverless web scraper'
    events:
      - schedule: rate(6 hours)
    image:
      uri: ${aws:accountId}.dkr.ecr.${aws:region}.amazonaws.com/wheelerrecommends-scraper:${param:sha}
    timeout: 300

package:
  exclude:
    - venv/**
