name: app

on:
  push:
    branches:
      - master
    paths:
      - app/**

  workflow_dispatch:

env:
  DOCKER_IMAGE_TAG: wheelerrecommends-scraper:${{ github.sha }}
  AWS_ECR_DOMAIN: 778263278211.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
  AWS_ECR_IMAGE_URI: ${{ env.AWS_ECR_DOMAIN }}/${{ env.DOCKER_IMAGE_TAG }}
  AWS_REGION: us-east-1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Authenticate to AWS ECR
        run: |
          aws ecr get-login-password --region ${{ env.AWS_REGION }} \
          | docker login --username AWS --password-stdin "${{ env.AWS_ECR_DOMAIN }}"

      - name: Docker Build
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_TAG }} .

      - name: Docker Tag
        run: |
          docker tag "${{ env.DOCKER_IMAGE_TAG }}" "${{ env.AWS_ECR_IMAGE_URI }}"

      - name: Docker Push
        run: |
          docker push "${{ env.AWS_ECR_IMAGE_URI }}"

      - name: Serverless Deploy
        uses: serverless/github-action@v3
        with:
          args: -c "cd app && serverless deploy --param=\"ecr-image-uri=${{ env.AWS_ECR_IMAGE_URI }}\""
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
